AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Thorfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/FileName:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/RescueEnsureAlignment:
  Enabled: false
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
