AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Thorfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/FileName:
  Enabled: false
